### ISSUE TITLE
已经更新为1.0.4.版本，使用Demo2报错

### ISSUE THREAD

**Issue by Pactortester** [Pactortester/swaggerjmx#3]
已经更新为1.0.4.版本，使用Demo2报错
`Traceback (most recent call last):
  File "/Users/milier/Code/PycharmProjects/QaTools/swaggerTojmx.py", line 37, in <module>
    swaggerJsonTojmx()
  File "/Users/milier/Code/PycharmProjects/QaTools/swaggerTojmx.py", line 34, in swaggerJsonTojmx
    conversion()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/swaggerjmx/convert.py", line 12, in conversion
    result = get_test_plan(swagger_url=ST.swagger_url, swagger_url_json_path=ST.swagger_url_json_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/swaggerjmx/get_swagger.py", line 35, in get_test_plan
    thread_group["port"] = str(host).split(":")[1]
IndexError: list index out of range`

_Originally posted by @milier110 in https://github.com/Pactortester/swaggerjmx/issues/1#issuecomment-659187293_

**Comment by Pactortester** [comment]
已修复请更新v1.0.4 验证
pip install swaggerjmx==1.0.4 -i https://pypi.org/simple

**Comment by Pactortester** [comment]
已修复 v1.0.5
