### ISSUE TITLE
TypeError: 'NoneType' object is not iterable错误

### ISSUE THREAD

**Issue by gdchaochao** [Pactortester/swaggerjmx#6]
Traceback (most recent call last):
  File "/Users/duckzheng/ceshijmeter/script/test_swaggerjmx.py", line 10, in <module>
    conversion()
  File "/usr/local/lib/python3.7/site-packages/swaggerjmx/convert.py", line 12, in conversion
    result = get_test_plan(swagger_url=ST.swagger_url, swagger_url_json_path=ST.swagger_url_json_path)
  File "/usr/local/lib/python3.7/site-packages/swaggerjmx/get_swagger.py", line 28, in get_test_plan
    for thread_group in thread_groups:
TypeError: 'NoneType' object is not iterable

运行简单的把json转jmx的例子，出现上面的错误。conversion 前面是不是少了个实例呢

![image](https://user-images.githubusercontent.com/3916495/103202000-44683200-492c-11eb-9007-9d132d5daf1e.png)

**Comment by Pactortester** [comment]
你的json串是从swagger上面复制下楼的吗？请确保json串格式正确哦

**Comment by gdchaochao** [comment]
> 你的json串是从swagger上面复制下楼的吗？请确保json串格式正确哦

果然是json不对，我还以为是找不到函数的问题。THX~

**Comment by Pactortester** [comment]
分享转发＋star,感谢！
